test:
  script:
  - apt-get update -qy
  - apt-get install -y wget build-essential imagemagick
  - wget --no-check-certificate -O - https://deb.nodesource.com/setup_5.x | bash
  - apt-get install -y nodejs
  - npm install
  - npm test